services:
  tempest-camera:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./output:/app/output

  tempest-timelapse:
    build: .
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    command: ["python", "timelapse.py"]
    profiles:
      - timelapse
